name: Publish NPM Package

on:
  push:
    tags:
      - 'typescript-v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: typescript
        run: npm ci

      - name: Build package
        working-directory: typescript
        run: npm run build

      - name: Publish to npm
        working-directory: typescript  
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}